package is.hi.hbv501g.kosmosinn.Kosmosinn.Entities;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * User Entity, an entity for the many users of Kosmosinn.
 * A User has an id (long), a username (String), a password (String)
 * and includes a ArrayList of Topics generated by the user (Topic Entities)
 * and includes a ArrayList of Comments generated by the user (Comment Entities) 
 */
@Entity
public class User {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long id;

	@Column(nullable = false, unique = true)
	public String username;

	@Column(nullable = false)
	public String password;

	@Column(nullable = false)
	public String role;

	@OneToMany(mappedBy = "user", orphanRemoval = true, cascade = CascadeType.ALL)
	//private List<Topic> topics = new ArrayList<>();
	private List<Long> topicIDs = new ArrayList<>();

	/*
	List<Topic>
	1. Topic - id, name, subject, List<Comments> ~ comment1, comment2, comment3

	List<long> topicsAuthoredId - long id

	 */


	@OneToMany(mappedBy = "user", orphanRemoval = true, cascade = CascadeType.ALL)
	//private List<Comment> comments = new ArrayList<>();
	private List<Long> commentIDs = new ArrayList<>();

	public User(String username, String password, String role)  {
		this.username = username;
		this.password = password;
		this.role = role;
	}

	public User() {}

	public long getId() {
		return id;
	}
	public String getUsername() {
		return username;
	}
	public String getPassword() { return password; }
	public String getRole() { return role; }

	//public List<Topic> getTopics() { return topics; }
	//public List<Comment> getComments() { return comments; }


	public List<Long> getTopicIDs() {
		return topicIDs;
	}

	public List<Long> getCommentIDs() {
		return commentIDs;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public void setRole(String role) { this.role = role; }
	//public void setTopics(List<Topic> topics) { this.topics = topics; }
	//public void setComments(List<Comment> comments) { this.comments = comments; }


	public void setTopicIDs(List<Long> topicIDs) {
		this.topicIDs = topicIDs;
	}

	public void setCommentIDs(List<Long> commentIDs) {
		this.commentIDs = commentIDs;
	}
}
